# Generated by Django 4.1.3 on 2022-11-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="category",
            new_name="categories",
        ),
    ]
