version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
  backend:
    build:
      context: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env_docker
    depends_on:
      - postgres
    tty: true
